const TMDB_BASE_URL = "https://api.themoviedb.org/3/";
export const TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p/w500";
export const SAMPLE_JSON = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
      genre_ids: [16, 10751, 12, 35],
      id: 1022789,
      original_language: "en",
      original_title: "Inside Out 2",
      overview:
        "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust, who’ve long been running a successful operation by all accounts, aren’t sure how to feel when Anxiety shows up. And it looks like she’s not alone.",
      popularity: 4599.773,
      poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
      release_date: "2024-06-11",
      title: "Inside Out 2",
      video: false,
      vote_average: 7.647,
      vote_count: 2038,
    },
    {
      adult: false,
      backdrop_path: "/fDmci71SMkfZM8RnCuXJVDPaSdE.jpg",
      genre_ids: [16, 10751, 35, 28],
      id: 519182,
      original_language: "en",
      original_title: "Despicable Me 4",
      overview:
        "Gru and Lucy and their girls — Margo, Edith and Agnes — welcome a new member to the Gru family, Gru Jr., who is intent on tormenting his dad. Meanwhile, Gru faces a new nemesis in Maxime Le Mal and his femme fatale girlfriend Valentina, forcing the family to go on the run.",
      popularity: 3483.085,
      poster_path: "/3w84hCFJATpiCO5g8hpdWVPBbmq.jpg",
      release_date: "2024-06-20",
      title: "Despicable Me 4",
      video: false,
      vote_average: 7.247,
      vote_count: 386,
    },
    {
      adult: false,
      backdrop_path: "/tncbMvfV0V07UZozXdBEq4Wu9HH.jpg",
      genre_ids: [28, 80, 53, 35],
      id: 573435,
      original_language: "en",
      original_title: "Bad Boys: Ride or Die",
      overview:
        "After their late former Captain is framed, Lowrey and Burnett try to clear his name, only to end up on the run themselves.",
      popularity: 3108.848,
      poster_path: "/nP6RliHjxsz4irTKsxe8FRhKZYl.jpg",
      release_date: "2024-06-05",
      title: "Bad Boys: Ride or Die",
      video: false,
      vote_average: 7.363,
      vote_count: 702,
    },
    {
      adult: false,
      backdrop_path: "/Akv9GlCCMrzcDkVz4ad8MdLl9DK.jpg",
      genre_ids: [16, 35, 10751, 12],
      id: 748783,
      original_language: "en",
      original_title: "The Garfield Movie",
      overview:
        "Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.",
      popularity: 1624.079,
      poster_path: "/p6AbOJvMQhBmffd0PIv0u8ghWeY.jpg",
      release_date: "2024-04-30",
      title: "The Garfield Movie",
      video: false,
      vote_average: 7.232,
      vote_count: 547,
    },
    {
      adult: false,
      backdrop_path: "/wNAhuOZ3Zf84jCIlrcI6JhgmY5q.jpg",
      genre_ids: [28, 12, 878],
      id: 786892,
      original_language: "en",
      original_title: "Furiosa: A Mad Max Saga",
      overview:
        "As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.",
      popularity: 1544.695,
      poster_path: "/iADOJ8Zymht2JPMoy3R7xceZprc.jpg",
      release_date: "2024-05-22",
      title: "Furiosa: A Mad Max Saga",
      video: false,
      vote_average: 7.646,
      vote_count: 2279,
    },
    {
      adult: false,
      backdrop_path: "/dn3gbDpXPSwC6saMJOHkCiFA9jn.jpg",
      genre_ids: [14, 12, 10751, 35],
      id: 974262,
      original_language: "en",
      original_title: "Descendants: The Rise of Red",
      overview:
        "After the Queen of Hearts incites a coup on Auradon, her rebellious daughter Red and Cinderella's perfectionist daughter Chloe join forces and travel back in time to try to undo the traumatic event that set Red's mother down her villainous path.",
      popularity: 1443.537,
      poster_path: "/8fYluTtB3b3HKO7KQa5tzrvGaps.jpg",
      release_date: "2024-07-11",
      title: "Descendants: The Rise of Red",
      video: false,
      vote_average: 7.17,
      vote_count: 174,
    },
    {
      adult: false,
      backdrop_path: "/wPNI1fd18z5TKBOK9Mv9Rfjb0j0.jpg",
      genre_ids: [53, 18, 28, 80],
      id: 729165,
      original_language: "en",
      original_title: "Out of Exile",
      overview:
        "Recently paroled thief Gabriel Russell tries to balance his life and mend a troubled family as an FBI agent hunts him down, along with his crew after a botched armored car robbery.",
      popularity: 1326.5,
      poster_path: "/jgF5XaXnJmOgMxulhy2k1f9LNNc.jpg",
      release_date: "2023-01-20",
      title: "Out of Exile",
      video: false,
      vote_average: 6.646,
      vote_count: 24,
    },
    {
      adult: false,
      backdrop_path: "/fqv8v6AycXKsivp1T5yKtLbGXce.jpg",
      genre_ids: [878, 12, 28],
      id: 653346,
      original_language: "en",
      original_title: "Kingdom of the Planet of the Apes",
      overview:
        "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
      popularity: 1376.798,
      poster_path: "/gKkl37BQuKTanygYQG1pyYgLVgf.jpg",
      release_date: "2024-05-08",
      title: "Kingdom of the Planet of the Apes",
      video: false,
      vote_average: 7.151,
      vote_count: 2036,
    },
    {
      adult: false,
      backdrop_path: "/rrwt0u1rW685u9bJ9ougg5HJEHC.jpg",
      genre_ids: [28, 35, 80],
      id: 280180,
      original_language: "en",
      original_title: "Beverly Hills Cop: Axel F",
      overview:
        "Forty years after his unforgettable first case in Beverly Hills, Detroit cop Axel Foley returns to do what he does best: solve crimes and cause chaos.",
      popularity: 981.812,
      poster_path: "/zszRKfzjM5jltiq8rk6rasKVpUv.jpg",
      release_date: "2024-06-20",
      title: "Beverly Hills Cop: Axel F",
      video: false,
      vote_average: 6.879,
      vote_count: 690,
    },
    {
      adult: false,
      backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      genre_ids: [878, 28, 35],
      id: 533535,
      original_language: "en",
      original_title: "Deadpool & Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      popularity: 1556.425,
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      release_date: "2024-07-24",
      title: "Deadpool & Wolverine",
      video: false,
      vote_average: 8.103,
      vote_count: 34,
    },
    {
      adult: false,
      backdrop_path: "/8fNBsXpgMvqk75SPsZzTmIqSRxY.jpg",
      genre_ids: [27, 53],
      id: 646683,
      original_language: "en",
      original_title: "The Exorcism",
      overview:
        "A troubled actor begins to unravel while shooting a supernatural horror film, leading his estranged daughter to wonder if he's slipping back into his past addictions or if there's something more sinister at play.",
      popularity: 848.098,
      poster_path: "/ar2h87jlTfMlrDZefR3VFz1SfgH.jpg",
      release_date: "2024-05-30",
      title: "The Exorcism",
      video: false,
      vote_average: 4.7,
      vote_count: 80,
    },
    {
      adult: false,
      backdrop_path: "/oSJV6nAfHzyE9v6oEAXmDjbko00.jpg",
      genre_ids: [14, 12],
      id: 943344,
      original_language: "zh",
      original_title: "地底怪物",
      overview: "",
      popularity: 824.773,
      poster_path: "/lWVwWRLqpS1OaNg7KT0ZecSW0PK.jpg",
      release_date: "2023-04-27",
      title: "Underground Monster",
      video: false,
      vote_average: 3.667,
      vote_count: 6,
    },
  ],
  total_pages: 45236,
  total_results: 904716,
};
